cache:
  key: ${CI_JOB_NAME}
  paths:
    - vendor/
    - bin/.phpunit/

stages:
  - test
  - quality

test:phpunit:
  stage: test
  image: "registry-gitlab.eolas.fr/docker/php-7.2-ci"
  script:
    - "SYMFONY_ENV=test composer install --no-interaction --no-scripts"
    - "php bin/phpunit --coverage-clover phpunit.coverage.xml --log-junit phpunit.report.xml"
  artifacts:
    paths:
      - phpunit.coverage.xml
      - phpunit.report.xml

quality:php-cs-fixer:
  stage: quality
  image: "registry-gitlab.eolas.fr/docker/php-7.2-ci"
  script:
    - "curl -L http://cs.sensiolabs.org/download/php-cs-fixer-v2.phar -o php-cs-fixer"
    - "echo 'If error use command: `./php-cs-fixer fix` in local to fix it'"
    - "php php-cs-fixer fix --config=.php_cs.dist -v --dry-run --using-cache=no"
  dependencies:
    - test:phpunit

quality:sonarqube:feature:
  stage: quality
  image:
    name: "newtmitch/sonar-scanner"
    entrypoint: [""]
  except:
    - master
  script:
    - "sonar-scanner
        -Dsonar.analysis.mode=preview
        -Dsonar.gitlab.commit_sha=$CI_BUILD_REF
        -Dsonar.gitlab.ref_name=$CI_BUILD_REF_NAME
        -Dsonar.gitlab.project_id=$CI_PROJECT_PATH
    "
  dependencies:
    - test:phpunit

quality:sonarqube:master:
  stage: quality
  image:
    name: "newtmitch/sonar-scanner"
    entrypoint: [""]
  only:
    - master
  script:
    - "sonar-scanner"
  dependencies:
    - test:phpunit
